### ISSUE TITLE
Attempted install with v3.5 python on mac. Error: Could not get HiyaCFW

### ISSUE THREAD

**Issue by RancidRocket** [mondul/HiyaCFW-Helper#79] opened 2019-11-09 00:05 UTC
i attempted install through homebrew python on mac, did exactly as instructed, and count not install. No clue why.
edit: tried on my brothers windows machine, same exact error

**Comment by RancidRocket** [comment] 2019-11-09 00:06
Status from GUI:

Checking NAND file...
- eMMC CID: CBA16EE2A1034D303046504100001500
- Console ID: 08A1982715099113

Downloading latest HiyaCFW release...
ERROR: Could not get HiyaCFW

**Comment by RancidRocket** [comment] 2019-11-09 04:46
some more looking around and i found that it cant make an ssl connection.
messages from the terminal here:objc[6018]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9ecbf3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10cf0af50). One of the two will be used. Which one is undefined.
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

**Comment by Kodtiz3D** [comment] 2019-11-09 14:40
This is already addressed in the README; https://github.com/mondul/HiyaCFW-Helper#macos
Please try this.
The fact you would get the same error on Windows is frankly not true, what is the exact error for the Windows machine?

**Comment by RancidRocket** [comment] 2019-11-09 15:01
The windows error was the same, sans the file paths. There was not a secure ssl connection made. I will check the FAQ now though

**Comment by RancidRocket** [comment] 2019-11-10 00:04
i just read the FAQ, i am using python installed with homebrew, but i will try the python installer from python.org

**Comment by mondul** [comment] 2019-11-14 14:52
SSL errors comes due missing local certificates or computer time misconfiguration. Cannot reproduce, closing ticket.

**Closed by mondul** 2019-11-14 14:52 UTC
