### ISSUE TITLE
JAP Launch dowload failed

### ISSUE THREAD

**Issue by david-zzj** [mondul/HiyaCFW-Helper#77] opened 2019-10-29 01:52 UTC
Whatever i use 3.51 or 3.50 helper, in the last state it showed:

Downloading JAP launcher...
ERROR: Could not download JAP launcher

**Comment by mondul** [comment] 2019-10-29 04:11
Could not reproduce with my japanese dump. Which error are you getting in the console?

**Comment by david-zzj** [comment] 2019-10-29 04:30
In the helper gui, download hiya.dsi was ok, at the last section, when download jap launcher, the error occurred. 

Is it my networks go something wrong? But I have try from yesterday to today morning.

**Comment by david-zzj** [comment] 2019-10-29 08:01
I redo the helper again, and take some screenshot. @mondul 

![1](https://user-images.githubusercontent.com/22125266/67748198-4d7a1c80-fa65-11e9-9dc6-70e3ce3c805f.jpg)
![2](https://user-images.githubusercontent.com/22125266/67748199-4e12b300-fa65-11e9-84a0-50d6b0b7e643.jpg)
![3](https://user-images.githubusercontent.com/22125266/67748196-4d7a1c80-fa65-11e9-9e93-5039a2267ff4.jpg)

**Comment by mondul** [comment] 2019-10-29 15:56
It's a network issue on your side (maybe you are using a proxy). Please get the launcher directly from [here](https://github.com/mondul/HiyaCFW-Helper/raw/master/launchers/JAP), place it at the same folder as the helper and run it again. Cannot reproduce, closing ticket.

**Closed by mondul** 2019-10-29 15:56 UTC
